import {deck,total,type Card} from './cards.ts';
export type BJHand={cards:Card[];bet:number;done:boolean;split:boolean;result?:string;credit?:number};
export type Blackjack={shoe:Card[];dealer:Card[];hands:BJHand[];active:number;phase:'player'|'dealer'|'done';credit:number};
export function finishBlackjack(g:Blackjack){const dv=total(g.dealer),dn=dv===21&&g.dealer.length===2;g.credit=0;for(const h of g.hands){const v=total(h.cards),natural=v===21&&h.cards.length===2&&!h.split;const credit=v>21?0:dn?(natural?h.bet:0):natural?h.bet*2.5:dv>21||v>dv?h.bet*2:v===dv?h.bet:0;h.credit=credit;h.result=v>21?'Bust':credit===h.bet?'Push':credit>h.bet?(natural?'Blackjack · 3:2':'Win'):'Dealer wins';g.credit+=credit;}g.phase='done';return g}
export function newBlackjack(stake:number,shoe=deck()):Blackjack{const d=[...shoe];const player=[d.shift()!],dealer=[d.shift()!];player.push(d.shift()!);dealer.push(d.shift()!);const g:Blackjack={shoe:d,dealer,hands:[{cards:player,bet:stake,done:false,split:false}],active:0,phase:'player',credit:0};return total(player)===21||total(dealer)===21?finishBlackjack(g):g}
export function canSplit(g:Blackjack){const h=g.hands[g.active];return g.phase==='player'&&g.hands.length===1&&h.cards.length===2&&Math.min(h.cards[0].rank,10)===Math.min(h.cards[1].rank,10)&&(h.cards[0].rank===14)===(h.cards[1].rank===14)}
function progress(g:Blackjack){while(g.active<g.hands.length&&g.hands[g.active].done)g.active++;if(g.active===g.hands.length){g.active=g.hands.length-1;g.phase='dealer';if(g.hands.every(h=>total(h.cards)>21))return finishBlackjack(g)}return g}
export function blackjackAction(state:Blackjack,action:'hit'|'stand'|'double'|'split'){if(state.phase!=='player')throw Error('Not player turn');const g=structuredClone(state),h=g.hands[g.active];if(action==='split'){if(!canSplit(g))throw Error('Cannot split');const aces=h.cards[0].rank===14;g.hands=h.cards.map(c=>({cards:[c,g.shoe.shift()!],bet:h.bet,done:aces,split:true}));g.hands.forEach(x=>{if(total(x.cards)===21)x.done=true});}
 else if(action==='stand')h.done=true;else{if(action==='double'&&h.cards.length!==2)throw Error('Cannot double');if(action==='double')h.bet*=2;h.cards.push(g.shoe.shift()!);if(total(h.cards)>=21||action==='double')h.done=true;}return progress(g)}
export function dealerStep(state:Blackjack){if(state.phase!=='dealer')throw Error('Not dealer turn');const g=structuredClone(state);if(total(g.dealer)<17)g.dealer.push(g.shoe.shift()!);return total(g.dealer)>=17?finishBlackjack(g):g}
