import {total,type Card} from './cards.ts';
export const redNumbers=new Set([1,3,5,7,9,12,14,16,18,19,21,23,25,27,30,32,34,36]);
export const wheelOrder=[0,32,15,19,4,21,2,25,17,34,6,27,13,36,11,30,8,23,10,5,24,16,33,1,20,14,31,9,22,18,29,7,28,12,35,3,26];
export type RouletteBet='red'|'black'|'odd'|'even'|'low'|'high'|'dozen1'|'dozen2'|'dozen3'|'number';
export function rouletteReturn(number:number,type:RouletteBet,stake:number,pick=0){if(type==='number')return number===pick?stake*36:0;if(number===0)return 0;const win=type==='red'?redNumbers.has(number):type==='black'?!redNumbers.has(number):type==='odd'?number%2===1:type==='even'?number%2===0:type==='low'?number<=18:type==='high'?number>=19:type==='dozen1'?number<=12:type==='dozen2'?number>=13&&number<=24:number>=25;return win?stake*(type.startsWith('dozen')?3:2):0}
export function randomInt(max:number){const a=new Uint32Array(1),limit=Math.floor(4294967296/max)*max;do{crypto.getRandomValues(a)}while(a[0]>=limit);return a[0]%max}
export const baccaratTotal=(cards:Card[])=>cards.reduce((n,c)=>n+(c.rank===14?1:c.rank>=10?0:c.rank),0)%10;
export function baccaratRound(shoe:Card[]){const d=[...shoe],player=[d.shift()!],banker=[d.shift()!];player.push(d.shift()!);banker.push(d.shift()!);const p=baccaratTotal(player),b=baccaratTotal(banker);if(p<8&&b<8){let third:number|undefined;if(p<=5){const c=d.shift()!;player.push(c);third=baccaratTotal([c])}const draw=third===undefined?b<=5:b<=2||(b===3&&third!==8)||(b===4&&third>=2&&third<=7)||(b===5&&third>=4&&third<=7)||(b===6&&third>=6&&third<=7);if(draw)banker.push(d.shift()!)}const pt=baccaratTotal(player),bt=baccaratTotal(banker);return {player,banker,winner:pt===bt?'tie' as const:pt>bt?'player' as const:'banker' as const}}
export function baccaratReturn(winner:'player'|'banker'|'tie',bet:'player'|'banker'|'tie',stake:number){if(winner==='tie')return bet==='tie'?stake*9:stake;if(winner!==bet)return 0;return bet==='banker'?stake*1.95:stake*2}
export function blackjackHint(hand:Card[],up:Card,canDouble:boolean,canSplit:boolean){const v=total(hand),u=up.rank===14?11:Math.min(up.rank,10),raw=hand.reduce((n,c)=>n+(c.rank===14?1:Math.min(c.rank,10)),0),soft=hand.some(c=>c.rank===14)&&v===raw+10;if(canSplit){const r=hand[0].rank;if(r===14||r===8)return 'Split';if(r===9&&[2,3,4,5,6,8,9].includes(u))return 'Split';if([2,3,7].includes(r)&&u<=7)return 'Split';if(r===6&&u<=6)return 'Split';if(r===4&&[5,6].includes(u))return 'Split'}if(soft){if(v>=19)return 'Stand';if(v===18){if(canDouble&&u>=3&&u<=6)return 'Double';return u<=8?'Stand':'Hit'}if(canDouble&&((v===17&&u>=3&&u<=6)||([15,16].includes(v)&&u>=4&&u<=6)||([13,14].includes(v)&&u>=5&&u<=6)))return 'Double';return 'Hit'}if(canDouble&&(v===11||(v===10&&u<=9)||(v===9&&u>=3&&u<=6)))return 'Double';if(v>=17||(v>=13&&u<=6)||(v===12&&u>=4&&u<=6))return 'Stand';return 'Hit'}
