import {useEffect,useRef,useState} from 'react';
import {total} from '@/lib/game/cards';
import {newBlackjack,blackjackAction,dealerStep,canSplit,type Blackjack} from '@/lib/game/blackjack';
import {blackjackHint} from '@/lib/game/casino';
import {GameCard} from './PokerArena';
import {Lightbulb,Info} from 'lucide-react';
export type CasinoProps={balance:number;setBalance:React.Dispatch<React.SetStateAction<number>>;onComplete:(r:{game:string;won:boolean;detail:string})=>void};
export function StakePicker({stake,setStake,busy}:{stake:number;setStake:(n:number)=>void;busy:boolean}){return <div className="stake-picker"><span>BET SIZE</span>{[100,250,500,1000].map(n=><button key={n} disabled={busy} aria-pressed={stake===n} onClick={()=>setStake(n)}>{n.toLocaleString()}</button>)}</div>}
export default function BlackjackTable({balance,setBalance,onComplete}:CasinoProps){const [g,setGame]=useState<Blackjack|null>(null),[stake,setStake]=useState(100),[coach,setCoach]=useState(false),[rules,setRules]=useState(false);const current=useRef<Blackjack|null>(null),complete=useRef(onComplete);complete.current=onComplete;
 const active=!!g&&g.phase!=='done',h=g?.hands[g.active];
 function commit(n:Blackjack){current.current=n;setGame(n);if(n.phase==='done'){setBalance(b=>b+n.credit);const spent=n.hands.reduce((s,x)=>s+x.bet,0);complete.current({game:'Blackjack',won:n.credit>spent,detail:n.hands.map((x,i)=>`Hand ${i+1}: ${x.result}`).join(' · ')+` · Net ${n.credit-spent}`})}}
 function deal(){if((current.current&&current.current.phase!=='done')||balance<stake)return;setBalance(b=>b-stake);commit(newBlackjack(stake))}
 function act(action:'hit'|'stand'|'double'|'split'){if(!g||current.current!==g||g.phase!=='player')return;const extra=action==='double'||action==='split'?g.hands[g.active].bet:0;if(balance<extra)return;if(extra)setBalance(b=>b-extra);commit(blackjackAction(g,action))}
 useEffect(()=>{if(g?.phase!=='dealer')return;const t=setTimeout(()=>{if(current.current===g)commit(dealerStep(g))},850);return()=>clearTimeout(t)},[g]);
 const split=!!g&&canSplit(g)&&balance>=(h?.bet||0),double=g?.phase==='player'&&h?.cards.length===2&&balance>=h.bet;
 return <section className="casino-room blackjack-room"><div className="casino-room-head"><div><span className="eyebrow">CLASSIC TABLE / 01</span><h2>Blackjack <i>21</i></h2><p>Trust the numbers. Play your hand.</p></div><div className="room-tools"><span className="quiet-badge">PAYS 3:2</span><button aria-label="Blackjack rules" onClick={()=>setRules(!rules)}><Info size={18}/></button><button aria-pressed={coach} onClick={()=>setCoach(!coach)}><Lightbulb size={16}/> Coach {coach?'on':'off'}</button></div></div>
 {rules&&<div className="rules-box">One shuffled 52-card deck per round. Dealer peeks for blackjack and stands on soft 17. Natural blackjack pays 3:2; split 21 pays 1:1. Double on any first two cards, including after a split. One split only; split aces receive one card each. No insurance or surrender. Strategy hints are a simplified guide, not a guarantee.</div>}
 <div className="blackjack-felt"><div className="dealer-identity"><span>♠</span><div>THE HOUSE<small>Stands on all 17s</small></div><b>{g?(g.phase==='player'?'?':total(g.dealer)):'—'}</b></div><div className="blackjack-cards dealer-cards">{(g?.dealer||[undefined,undefined]).map((c,i)=><GameCard key={i} card={c} back={g?.phase==='player'&&i===1} index={i}/>)}</div><div className="felt-brand"><span>RIVER CLUB</span><small>BLACKJACK PAYS 3 TO 2</small><div className="felt-arc"/></div><div className="blackjack-hands">{(g?.hands||[{cards:[],bet:stake,done:false,split:false}]).map((hand,i)=><div key={i} className={`blackjack-hand ${g?.phase==='player'&&g.active===i?'hand-active':''}`}><div className="blackjack-cards">{(hand.cards.length?hand.cards:[undefined,undefined]).map((c,j)=><GameCard key={j} card={c} index={j}/>)}</div><div className="hand-label"><span>{g&&g.hands.length>1?`HAND ${i+1}`:'YOUR HAND'}</span><b>{hand.cards.length?total(hand.cards):'—'}</b><small>{hand.result||`${hand.bet} chips`}</small></div></div>)}</div></div>
 <div className="casino-actionbar"><div className="round-message" role="status">{!g?'Take a seat. The next hand is yours.':g.phase==='dealer'?'Dealer is revealing and drawing…':g.phase==='done'?`${g.hands.map(x=>x.result).join(' / ')} · ${g.credit} chips returned`:`Your move${g.hands.length>1?` · Hand ${g.active+1}`:''}`}{coach&&g?.phase==='player'&&h&&<small className="coach-hint"><Lightbulb size={13}/> Suggested: {blackjackHint(h.cards,g.dealer[0],!!double,split)} · uses your cards and dealer upcard</small>}</div><div className="casino-buttons">{!active?<button className="gold-button" onClick={deal} disabled={balance<stake}>Deal hand · {stake}</button>:<><button onClick={()=>act('hit')} disabled={g?.phase!=='player'}>Hit</button><button className="gold-button" onClick={()=>act('stand')} disabled={g?.phase!=='player'}>Stand</button><button onClick={()=>act('double')} disabled={!double}>Double</button><button onClick={()=>act('split')} disabled={!split}>Split</button></>}</div></div><StakePicker stake={stake} setStake={setStake} busy={active}/>
 </section>
}
