'use client';
import {useState} from 'react';
import {ArrowRight,Check,ChevronLeft,ChevronRight,Sparkles,Users,Trophy} from 'lucide-react';
export const CHARACTERS=[{name:'Atlas',title:'THE TACTICIAN',color:'#9fbefa',bio:'A steady gaze. A patient game. Make every move your own.'},{name:'Mika',title:'THE OBSERVER',color:'#ed9dcc',bio:'Read the room. Find your moment. Take your seat in style.'},{name:'Nova',title:'THE CHALLENGER',color:'#88e6c6',bio:'Bring your confidence to the table. Make the night yours.'}];
export function Particles(){return <div className="game-particles" aria-hidden="true">{Array.from({length:20},(_,i)=><i key={i} style={{left:`${(i*37)%100}%`,top:`${(i*19)%100}%`,animationDelay:`${i*-.7}s`,animationDuration:`${9+i%7}s`}}/>)}</div>}
export function HumanCharacter({index,pose='idle',className=''}:{index:number;pose?:string;className?:string}){const row=pose==='thinking'?1:pose==='call'||pose==='check'?2:pose==='win'?3:0;return <div className={`human-render motion-${pose} ${className}`} role="img" aria-label={`${CHARACTERS[index].name}, ${pose}`}><div className="human-shadow"/>{[0,1,2,3].map(r=><div key={r} className={`human-layer ${r===row?'pose-visible':''}`} style={{backgroundPosition:`${index*50}% ${r*100/3}%`}}/>)}</div>}
export default function CharacterSelect({selected,onSelect,onEnter,onTournament,resume=false}:{selected:number;onSelect:(i:number)=>void;onEnter:()=>void;onTournament:()=>void;resume?:boolean}){const [tilt,setTilt]=useState({x:0,y:0});const c=CHARACTERS[selected];return <section className="character-lobby" style={{'--character-color':c.color} as React.CSSProperties} onPointerMove={e=>{if(e.pointerType==='mouse'){const b=e.currentTarget.getBoundingClientRect();setTilt({x:(e.clientX-b.left)/b.width-.5,y:(e.clientY-b.top)/b.height-.5})}}} onPointerLeave={()=>setTilt({x:0,y:0})}>
 <img className="lobby-environment" src="/assets/neon-arena.webp" alt=""/><div className="lobby-shade"/><div className="lobby-beam beam-one"/><div className="lobby-beam beam-two"/><Particles/>
 <div className="lobby-copy"><div className="season-tag"><Sparkles size={13}/> PLAYER SELECT / 01 <span>01</span></div><h1>YOUR SEAT.<br/>YOUR <em>RULES.</em></h1><p>Choose your identity. Read the room.<br/>Make your next move count.</p><div className="lobby-modes"><span><Users size={14}/> 4-seat poker</span><span>♠ Free-play chips</span></div>
 <div className="roster-heading"><span>01 — CHOOSE YOUR CHARACTER</span><small>3 AVAILABLE</small></div><div className="character-roster" role="group" aria-label="Choose your character">{CHARACTERS.map((ch,i)=><button key={ch.name} className={`roster-choice ${selected===i?'roster-selected':''}`} aria-pressed={selected===i} onClick={()=>onSelect(i)} style={{'--choice-color':ch.color} as React.CSSProperties}><div className="roster-face" style={{backgroundPosition:`${i*50}% 0%`}}/><span>{ch.name}</span>{selected===i?<Check size={13}/>:<span className="roster-number">0{i+1}</span>}</button>)}</div>
 <button className="enter-game" onClick={onEnter}><span>{resume?'RETURN TO TABLE':'ENTER THE ROOM'}</span><ArrowRight size={22}/></button><div className="lobby-fineprint">Character choice is cosmetic. Same rules. Your style.</div></div>
 <div className="character-stage" style={{transform:`perspective(1200px) rotateY(${tilt.x*7}deg) rotateX(${-tilt.y*3}deg)`}}><div className="stage-halo"/><div className="stage-orbit"/><div className="stage-light"/>{CHARACTERS.map((ch,i)=><div key={ch.name} aria-hidden={selected!==i} className={`selection-model ${selected===i?'selected-model':''}`}><HumanCharacter index={i}/></div>)}<div className="character-title" key={selected}><small>{c.title}</small><h2>{c.name}</h2><p>{c.bio}</p><span className="selected-indicator"><Check size={12}/> CHARACTER SELECTED</span></div><button className="character-cycle cycle-left" aria-label="Previous character" onClick={()=>onSelect((selected+2)%3)}><ChevronLeft size={23}/></button><button className="character-cycle cycle-right" aria-label="Next character" onClick={()=>onSelect((selected+1)%3)}><ChevronRight size={23}/></button></div>
 <button className="lobby-event" onClick={onTournament}><Trophy size={25}/><span><small>THE NEXT CHALLENGE</small><strong>Sunday Majors</strong></span><span className="event-prize">25K<small>DEMO CHIPS</small></span><ArrowRight size={18}/></button>
 <div className="lobby-bottom"><span>FREE PLAY · PRACTICE OPPONENTS</span><span>SELECT → TAKE A SEAT → PLAY</span></div></section>}
