import {useEffect,useRef,useState} from 'react';
import {label,type Card} from '@/lib/game/cards';
import {newPoker,pokerAction,botDecision,legal,pot,toCall,type Poker,type Action,type Difficulty} from '@/lib/game/poker';
import CharacterSelect,{CHARACTERS,HumanCharacter} from './CharacterSelect';
import {History,Info,Trophy} from 'lucide-react';
export function GameCard({card,back=false,index=0}:{card?:Card;back?:boolean;index?:number}){return <div className={`game-card ${back||!card?'face-down':['♥','♦'].includes(card.suit)?'suit-red':''}`} style={{animationDelay:`${index*75}ms`}} aria-label={!card||back?'Face-down card':`${label(card.rank)} ${card.suit}`}>{!card||back?<span className="card-monogram">R</span>:<><span className="rank">{label(card.rank)}<small>{card.suit}</small></span><span className="big-suit">{card.suit}</span><span className="corner-rank">{label(card.rank)}</span></>}</div>}
type Props={balance:number;setBalance:React.Dispatch<React.SetStateAction<number>>;onTournament:()=>void;onComplete?:(r:{game:string;won:boolean;detail:string})=>void};
export default function PokerArena({balance,setBalance,onTournament,onComplete}:Props){
 const [entered,setEntered]=useState(false),[selected,setSelected]=useState(()=>Math.max(0,Math.min(2,Math.trunc(Number(localStorage.getItem('river-character')))||0))),[g,setGame]=useState<Poker|null>(null),[difficulty,setDifficulty]=useState<Difficulty>('standard'),[history,setHistory]=useState(false),[rules,setRules]=useState(false),[hand,setHand]=useState(0);
 const current=useRef<Poker|null>(null),buyin=useRef(0),complete=useRef(onComplete);complete.current=onComplete;
 function commit(next:Poker){current.current=next;setGame(next);if(next.done){setBalance(b=>b+next.seats[0].stack);complete.current?.({game:'Poker',won:next.seats[0].stack>buyin.current,detail:`${next.result} · Net ${next.seats[0].stack-buyin.current}`})}}
 function start(){if((current.current&&!current.current.done)||balance<100)return;const amount=Math.min(2000,Math.floor(balance));buyin.current=amount;setBalance(b=>b-amount);setHand(n=>n+1);commit(newPoker(amount,hand%4));}
 function act(action:Action){if(!g||current.current!==g||g.actor!==0||g.done)return;commit(pokerAction(g,action))}
 useEffect(()=>{if(!g||g.done||g.actor===0)return;const timer=setTimeout(()=>{if(current.current!==g)return;commit(pokerAction(g,botDecision(g,difficulty)));},800+Math.random()*550);return()=>clearTimeout(timer)},[g,difficulty]);
 const select=(n:number)=>{setSelected(n);localStorage.setItem('river-character',String(n))};
 if(!entered)return <CharacterSelect selected={selected} onSelect={select} onEnter={()=>setEntered(true)} onTournament={onTournament} resume={!!g&&!g.done}/>;
 const actions=g?legal(g):[],yourTurn=!!g&&!g.done&&g.actor===0;const status=!g?'Choose your challenge and take a seat.':g.done?g.result:yourTurn?`${toCall(g)?`${toCall(g)} to call`:'You can check'} · ${['Pre-flop','Flop','Turn','River'][g.street]}`:`${g.seats[g.actor].name} is thinking…`;
 return <div className={`casino-layout immersive-table refined-poker ${history?'history-open':''}`}><section className="arena-shell"><div className="arena-toolbar"><div className="room-title"><span className="room-emblem">♠</span><div><span className="eyebrow">THE SIGNATURE TABLE</span><h2>Midnight Hold’em</h2></div></div><div className="table-tags"><button className="game-menu-button" onClick={()=>setEntered(false)}>Characters</button><button className="game-menu-button" onClick={()=>setHistory(!history)}><History size={14}/> History</button><button className="icon-button" aria-label="Poker rules" onClick={()=>setRules(!rules)}><Info size={18}/></button></div></div>{rules&&<div className="arena-rules">Four-seat fixed-limit Hold’em. Blinds 25 / 50; bets and raises add 100, maximum three per street. Calls may use your remaining stack; side pots are settled independently. Up to 2,000 chips are reserved for a hand; your remaining stack is returned at the end. Bot stacks reset each hand. Bots estimate equity using their own cards and public cards only. Practice chips, no cash value.</div>}
 <div className="casino-scene"><img className="room-art" src="/assets/neon-arena.webp" alt=""/><div className="scene-vignette"/><div className="arena-table"><div className="table-felt"><span>RIVER CLUB</span><small>PRIVATE TABLE · EST. 2024</small></div></div><div className="hand-marker">HAND {String(hand).padStart(3,'0')} <span>•</span> BLINDS 25 / 50</div>
 {[0,1,2].map(i=>{const s=g?.seats[i+1],active=g&&!g.done&&g.actor===i+1;const pose=s?.folded?'fold':g?.done&&s?.payout?'win':active?'thinking':s?.action.startsWith('Raise')||s?.action.startsWith('Bet')||s?.action.startsWith('Call')?'call':s?.action==='Check'?'check':'idle';return <div key={i} className={`human-seat human-seat-${i} state-${pose} ${active?'is-active':''} ${s?.folded?'is-folded':''}`}><HumanCharacter index={i} pose={pose}/><div className="opponent-cards">{s&&!s.folded&&s.cards.map((c,j)=><GameCard key={`${hand}-${j}`} card={c} back={!g?.done||!g.showdown} index={j}/>)}</div><div className="player-nameplate"><span className="player-name">{['Atlas','Mika','Nova'][i]} <small>BOT</small></span><strong>{(s?.stack??2000).toLocaleString()} <span>◉</span></strong>{active&&<div className="turn-progress"/>}</div><div className="player-action" aria-live="polite">{active?'Thinking…':s?.action||['Patient & balanced','Selective & cautious','Pressure & bluffs'][i]}</div>{g&&g.button===i+1&&<span className="dealer-button">D</span>}</div>})}
 <div className="community-zone"><div className="pot-label"><span>{g?.done?'FINAL POT':'IN THE MIDDLE'}</span><strong key={g?pot(g):0}>{g?pot(g).toLocaleString():0} <small>CHIPS</small></strong></div><div className="community-cards">{Array.from({length:5},(_,i)=>g?.board[i]?<GameCard key={`${hand}-${i}`} card={g.board[i]} index={i}/>:<div className="card-slot" key={i}>♠</div>)}</div><div className="street-label">{g?g.done?'HAND COMPLETE':['PRE-FLOP','FLOP','TURN','RIVER'][g.street]:'A LITTLE INSTINCT. A LITTLE STRATEGY.'}</div></div>
 <div className={`your-seat ${g?.done&&g.seats[0].payout?'you-win':''}`}><div className="your-hole-cards">{[0,1].map(i=><GameCard key={`${hand}-${i}`} card={g?.seats[0].cards[i]}/>)}</div><div className="you-nameplate"><span className="your-character-icon" style={{backgroundPosition:`${selected*50}% 0%`}}/><span className="your-character-name">{CHARACTERS[selected]?.name||'Atlas'}<small>YOU {g?.button===0?'· DEALER':''}</small></span><div><strong>{(g?.seats[0].stack??0).toLocaleString()}</strong><small>{g?.seats[0].action||'Table stack'}</small></div></div></div>
 </div><div className="game-controls"><div className="turn-status"><span className={`turn-indicator ${!yourTurn?'waiting':''}`}/><div><span className="eyebrow">{g?.done?'HAND RESULT':yourTurn?'YOUR MOVE':'PRACTICE TABLE'}</span><p role="status">{status}</p></div></div><div className="poker-buttons">{!g||g.done?<><select aria-label="Bot difficulty" value={difficulty} onChange={e=>setDifficulty(e.target.value as Difficulty)}><option value="casual">Casual bots</option><option value="standard">Standard bots</option><option value="expert">Expert bots</option></select><button className="gold-button" disabled={balance<100} onClick={start}>{g?'Next hand':'Deal hand'} · {Math.min(Math.floor(balance),2000).toLocaleString()}</button></>:<><button className="fold-button" disabled={!yourTurn} onClick={()=>act('fold')}>Fold</button><button className="check-button" disabled={!yourTurn} onClick={()=>act(actions.includes('check')?'check':'call')}>{toCall(g,0)?`Call ${Math.min(toCall(g,0),g.seats[0].stack)}`:'Check'}</button><button className="gold-button" disabled={!yourTurn||!actions.includes('raise')} onClick={()=>act('raise')}>{g.bet?'Raise +100':'Bet 100'}</button></>}</div></div></section><aside className="game-sidebar"><button className="close-history" onClick={()=>setHistory(false)}>Close ×</button><div className="history-panel"><h3><History size={16}/> Hand history</h3><div className="history-scroll" role="log">{g?.log.map((line,i)=><div className="history-entry" key={i}>{line}</div>)||<p>Your next hand starts here.</p>}</div>{g?.done&&<p><Trophy size={16}/> {g.result}</p>}</div></aside></div>
}
