'use client';
import {useEffect,useRef,useState,lazy,Suspense} from 'react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Toaster,toast} from 'sonner';
import {Globe2,Trophy,Users,ArrowUpRight,Wallet,ShieldCheck,Spade,Coins,CalendarDays,ChevronRight,Send,Flame,LayoutGrid,CircleDot,Diamond,BookOpen} from 'lucide-react';
import PokerArena from '@/components/game/PokerArena';
import DemoCenter,{useDemo} from '@/components/demo/DemoCenter';
import './demo.css';
import BlackjackTable from '@/components/game/BlackjackTable';
import {Roulette,Baccarat} from '@/components/game/CasinoGames';
import CasinoLobby from '@/components/game/CasinoLobby';
const DesignVision=lazy(()=>import('@/components/design/DesignVision'));
import '@/components/design/design-vision.css';

type Provider={request:(a:{method:string;params?:unknown[]})=>Promise<any>;on?:(e:string,fn:(v:any)=>void)=>void;removeListener?:(e:string,fn:(v:any)=>void)=>void};
const provider=()=> (window as unknown as {ethereum?:Provider}).ethereum;
const events=[{id:1,name:'Sunday Majors',type:'WEEKLY TOURNAMENT',prize:'25,000',time:'Sunday · 18:00 UTC',size:'6-seat poker',fee:250},{id:2,name:'World Circuit',type:'GLOBAL SERIES',prize:'100,000',time:'Saturday · 20:00 UTC',size:'Regional qualifiers',fee:500},{id:3,name:'The First Hand',type:'BEGINNER EVENT',prize:'5,000',time:'Daily · 16:00 UTC',size:'New players welcome',fee:0}];
export default function Home(){
 const demo=useDemo();
 const [tab,setTab]=useState(()=>window.location.pathname==='/design'?'design':'lobby'),[balance,setBalance]=useState(10000),[ready,setReady]=useState(false),[wallet,setWallet]=useState(''),[connecting,setConnecting]=useState(false),[modal,setModal]=useState(''),[registered,setRegistered]=useState<number[]>([]),[selectedEvent,setSelectedEvent]=useState(1),[region,setRegion]=useState('Europe'),[queued,setQueued]=useState(false),[queueResult,setQueueResult]=useState(false),[messages,setMessages]=useState<{name:string;text:string}[]>([{name:'River Club',text:'Welcome to the lounge. This is your local demo chat — invite friends when multiplayer is connected.'}]),[message,setMessage]=useState(''),[club,setClub]=useState(false),[tx,setTx]=useState(''),[chainPending,setChainPending]=useState(false);
 const [pokerVisited,setPokerVisited]=useState(false);
 useEffect(()=>{if(tab==='poker')setPokerVisited(true)},[tab]);
 const lock=useRef(false);const queueTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('river-club-v1')||'null');if(saved){if(Number.isFinite(saved.balance)&&saved.balance>=0)setBalance(saved.balance);if(Array.isArray(saved.registered))setRegistered(saved.registered.filter((x:unknown)=>typeof x==='number'));setClub(saved.club===true)}}catch{}setReady(true);const p=provider();const change=(accounts:string[])=>setWallet(accounts[0]||'');p?.on?.('accountsChanged',change);return()=>{p?.removeListener?.('accountsChanged',change);if(queueTimer.current)clearTimeout(queueTimer.current)}},[]);
 useEffect(()=>{if(ready)localStorage.setItem('river-club-v1',JSON.stringify({balance,registered,club}))},[balance,registered,club,ready]);
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const controller=new AbortController();Promise.resolve(ctx.registerTool({name:'open_game_view',description:'Open a River Club game or event view without placing a bet.',inputSchema:{type:'object',properties:{view:{type:'string',enum:['lobby','poker','blackjack','roulette','baccarat','tournaments','world','social','clubhouse']}},required:['view'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:{view:string})=>{if(!['lobby','poker','blackjack','roulette','baccarat','tournaments','world','social','clubhouse'].includes(input.view))throw Error('Unknown view');setTab(input.view);return {view:input.view}}},{signal:controller.signal})).catch(()=>{});return()=>controller.abort()},[]);
 async function connect(){const p=provider();if(!p){setModal('wallet');return}setConnecting(true);try{const a=await p.request({method:'eth_requestAccounts'});setWallet(a[0]||'');toast.success('Wallet connected. No funds requested.')}catch(e){toast.error(e instanceof Error?e.message:'Wallet connection declined')}finally{setConnecting(false)}}
 function register(){const e=events.find(x=>x.id===selectedEvent)!;if(registered.includes(e.id)||balance<e.fee)return;setBalance(b=>b-e.fee);setRegistered(r=>[...r,e.id]);toast.success(`Registered for ${e.name} in this demo`);setModal('')}
 function queue(){setQueued(true);setQueueResult(false);queueTimer.current=setTimeout(()=>{setQueued(false);setQueueResult(true)},3500)}
 async function chainJoin(){const address=import.meta.env.VITE_EVENT_CONTRACT;const chain=import.meta.env.VITE_CHAIN_ID||'0x14a34';if(!address||!/^0x[0-9a-fA-F]{40}$/.test(address)){toast.error('Deploy RiverEvents.sol and configure the event contract first.');return}const p=provider();if(!p||!wallet){await connect();return}setChainPending(true);try{const id=await p.request({method:'eth_chainId'});if(id.toLowerCase()!==chain.toLowerCase())await p.request({method:'wallet_switchEthereumChain',params:[{chainId:chain}]});const code=await p.request({method:'eth_getCode',params:[address,'latest']});if(code==='0x')throw Error('No contract deployed at the configured address');const selector=await p.request({method:'web3_sha3',params:['0x6a6f696e2875696e7432353629']});const hash=await p.request({method:'eth_sendTransaction',params:[{from:wallet,to:address,data:selector.slice(0,10)+selectedEvent.toString(16).padStart(64,'0'),value:'0x0'}]});setTx(hash);toast.success('Check-in transaction submitted. Use your wallet to track confirmation.')}catch(e){toast.error(e instanceof Error?e.message:'Transaction failed or declined')}finally{setChainPending(false)}}
 return <><Toaster theme="dark" richColors/><header><div className="brand"><b>♠</b><span>RIVER<em>CLUB</em></span></div><div className="topmeta"><span className="system-dot"/> THE PRIVATE PLAY COLLECTION</div><button className="wallet" onClick={connect} disabled={connecting}><Wallet size={16}/>{connecting?'Connecting…':wallet?wallet.slice(0,6)+'…'+wallet.slice(-4):'Connect wallet'}</button></header><main className="shell game-app-shell"><div className="titlebar"><div className="chipbalance"><Coins size={17}/><div><span className="help">PLAY CHIPS</span><strong>{balance.toLocaleString()}</strong></div><button className="secondary" aria-label="Refill demo chips" onClick={()=>{setBalance(b=>b+10000);toast.success('10,000 free demo chips added')}}>+</button></div></div>
 <Tabs value={tab} onValueChange={setTab}><TabsList className="tabbar"><TabsTrigger value="lobby"><LayoutGrid size={21}/>Lobby</TabsTrigger><TabsTrigger value="poker"><Spade size={23}/>Poker</TabsTrigger><TabsTrigger value="blackjack"><Coins size={23}/>Blackjack</TabsTrigger><TabsTrigger value="roulette"><CircleDot size={23}/>Roulette</TabsTrigger><TabsTrigger value="baccarat"><Diamond size={23}/>Baccarat</TabsTrigger><TabsTrigger value="tournaments"><Trophy size={23}/>Events</TabsTrigger><TabsTrigger value="world"><Globe2 size={23}/>World</TabsTrigger><TabsTrigger value="social"><Users size={23}/>Lounge</TabsTrigger><TabsTrigger value="clubhouse"><Flame size={23}/>Clubhouse</TabsTrigger><TabsTrigger value="design"><BookOpen size={21}/>Design</TabsTrigger></TabsList>
 <TabsContent value="lobby"><CasinoLobby onOpen={setTab}/></TabsContent>
 <TabsContent value="poker" forceMount className="persistent-poker">{(tab==='poker'||pokerVisited)&&<PokerArena balance={balance} setBalance={setBalance} onTournament={()=>setTab('tournaments')} onComplete={demo.record}/>}</TabsContent>
 <TabsContent value="blackjack" forceMount className="persistent-game"><BlackjackTable balance={balance} setBalance={setBalance} onComplete={demo.record}/></TabsContent>
 <TabsContent value="roulette" forceMount className="persistent-game"><Roulette balance={balance} setBalance={setBalance} onComplete={demo.record}/></TabsContent>
 <TabsContent value="baccarat" forceMount className="persistent-game"><Baccarat balance={balance} setBalance={setBalance} onComplete={demo.record}/></TabsContent>
 <TabsContent value="tournaments"><div className="sectionhead" style={{marginTop:0}}><div><h2>TOURNAMENT ARENA</h2><button className="secondary" onClick={()=>setTab('clubhouse')}>Play demo circuit · Clubhouse</button><p className="help">Demo event schedules. Registration is saved on this device. Tournament rounds are not live.</p></div></div><div className="eventgrid">{events.map(e=><article className="event" key={e.id}><span className="eyebrow">{e.type}</span><h2>{e.name}</h2><p>{e.size}</p><div className="prize">{e.prize} <small>demo chips</small></div><div className="row"><CalendarDays size={18}/><span>{e.time}</span></div><div className="row"><span>Demo entry</span><strong>{e.fee?e.fee+' chips':'Free'}</strong></div><button className="primary" disabled={registered.includes(e.id)} onClick={()=>{setSelectedEvent(e.id);setModal('event')}}>{registered.includes(e.id)?'Registered on this device':'Reserve a seat'}</button><button className="help" style={{marginTop:16,background:'none',border:0,textDecoration:'underline'}} onClick={()=>{setSelectedEvent(e.id);setModal('chain')}}>Onchain event check-in <ArrowUpRight size={13} style={{display:'inline'}}/></button></article>)}</div><div className="box" style={{marginTop:24}}><ShieldCheck size={22} className="iconbox"/><h3>Your wallet. Your identity.</h3><p>Connect an EVM wallet and use the included tournament contract for onchain attendance. Game chips stay in the demo and have no cash value. Contract deployment and event creation are required before check-in.</p></div></TabsContent>
 <TabsContent value="world"><div className="world"><Globe2 size={88} strokeWidth={.8}/><span className="eyebrow">World match · practice preview</span><h2 style={{marginTop:14}}>FIND YOUR NEXT RIVAL</h2><p>Pick your region and take a seat against practice opponents.</p><div className="regionbuttons">{['Europe','Asia Pacific','Americas'].map(r=><button disabled={queued} className={'secondary '+(region===r?'selected':'')} key={r} onClick={()=>{setRegion(r);setQueueResult(false)}}>{r}</button>)}</div>{queued?<><p role="status">Preparing a {region} practice table…</p><button className="secondary" onClick={()=>{if(queueTimer.current)clearTimeout(queueTimer.current);setQueued(false)}}>Cancel queue</button></>:queueResult?<><p role="status">Practice table ready · You + 3 bots · {region}</p><button className="primary" onClick={()=>{setTab('poker');setQueueResult(false)}}>Take your seat <ChevronRight size={16}/></button></>:<button className="primary" onClick={queue}>Find a practice match <ArrowUpRight size={16}/></button>}<p className="help" style={{marginTop:30}}>This preview simulates matchmaking. Real players, regional servers, and ranked results are not connected.</p></div></TabsContent>
 <TabsContent value="social"><div className="social"><section className="box"><div className="boxhead"><h2>The lounge</h2><button className="secondary" onClick={()=>setTab('clubhouse')}>Friends & rooms</button><span className="badge">LOCAL DEMO</span></div><p>Good conversation starts with a good hand.</p><div className="chatlog" aria-live="polite">{messages.map((m,i)=><div className="chatmessage" key={i}><strong>{m.name}</strong><p>{m.text}</p></div>)}</div><form className="chatform" onSubmit={e=>{e.preventDefault();if(!message.trim())return;setMessages(m=>[...m,{name:wallet?wallet.slice(0,6)+'…':demo.state.name,text:message.trim()},{name:'Atlas · simulated reply',text:/hello|hi|hey/i.test(message)?'Welcome to the table. Want to try the Clubhouse circuit?':'Message received in this local demo. Your crew and private room controls are in the Clubhouse.'}]);setMessage('')}}><input aria-label="Chat message" value={message} maxLength={500} onChange={e=>setMessage(e.target.value)} placeholder="Say hello to the table…"/><button className="primary" aria-label="Send message" disabled={!message.trim()}><Send size={17}/></button></form><p className="help">Messages stay in this session. Atlas replies are scripted demo responses, not another person.</p></section><aside><div className="box"><Users size={28} className="iconbox"/><h2>The Night Owls</h2><p>A club for late hands and good company. Try joining this demo club.</p><button className="primary full" onClick={()=>{setClub(!club);toast.success(club?'Left the demo club':'Joined The Night Owls')}}>{club?'Leave club':'Join the club'}</button></div><div className="box"><h3>Bring your crew</h3><p>Share the app link with a friend. Access follows the site’s sharing settings.</p><button className="secondary full" onClick={async()=>{try{await navigator.clipboard.writeText(location.origin);toast.success('App link copied')}catch{toast.error('Copy the page address from your browser')}}}>Copy app link</button></div></aside></div></TabsContent>
 <TabsContent value="design"><Suspense fallback={<p className="vision-note">Opening design viewer…</p>}><DesignVision onClose={()=>{setTab('lobby');if(window.location.pathname==='/design')window.history.replaceState(null,'','/')}}/></Suspense></TabsContent><TabsContent value="clubhouse"><DemoCenter model={demo} balance={balance} setBalance={setBalance} onPlay={()=>setTab('poker')}/></TabsContent></Tabs><footer className="footer"><span>♠ RIVER CLUB · A place at the table.</span><span>Play-money prototype · No deposits or withdrawals · 18+</span></footer></main>
 <Dialog open={!!modal} onOpenChange={open=>{if(!open)setModal('')}}><DialogContent className="dialogbody"><DialogHeader><DialogTitle>{modal==='rules'?'The Green Room rules':modal==='event'?'Reserve your tournament seat':modal==='chain'?'Onchain check-in':'Connect your wallet'}</DialogTitle><DialogDescription>{modal==='rules'?'A simple Texas Hold’em practice table.':modal==='event'?'Demo registration, using free chips.':modal==='chain'?'Record tournament attendance with your EVM wallet.':'An EVM browser wallet is needed for this feature.'}</DialogDescription></DialogHeader>{modal==='rules'?<><p>The small and big blinds are 25 and 50 chips. You receive two hole cards; five community cards appear across the flop, turn, and river. The best five-card poker hand wins. Equal hands split the pot.</p><p>Fixed-limit practice with 25/50 blinds, 100-chip raises, three raises per street, short-stack calls and side pots. Bots use visible-card equity and pot odds.</p><p>Cards are shuffled locally with browser cryptographic randomness. This is not a verifiable onchain shuffle. All chips are free and have no cash value.</p></>:modal==='event'?<><h2>{events.find(e=>e.id===selectedEvent)?.name}</h2><p>Entry: {events.find(e=>e.id===selectedEvent)?.fee||0} demo chips. This reserves a seat locally; it does not enter a live tournament.</p><button className="primary" onClick={register} disabled={balance<(events.find(e=>e.id===selectedEvent)?.fee||0)}>Confirm registration</button></>:modal==='chain'?<><p>{import.meta.env.VITE_EVENT_CONTRACT?'Configured for the event registry. A wallet transaction is required; network gas may apply.':'The tournament contract is included in the project but has not been configured for this preview.'}</p><button className="primary" disabled={chainPending||!import.meta.env.VITE_EVENT_CONTRACT} onClick={chainJoin}>{chainPending?'Waiting for wallet…':'Submit onchain check-in'}</button>{tx&&<p style={{overflowWrap:'anywhere'}}>Submitted transaction (confirmation pending): {tx}</p>}</>:<p>Open River Club in a browser with an injected EVM wallet, such as MetaMask. You can play all demo games without a wallet.</p>}</DialogContent></Dialog></>
}
